spring:
  datasource:
    url: jdbc:h2:mem:restaurant
    driverClassName: org.h2.Driver
    username: sa
    password: 1111
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      #  We shouldn't drop DB to keep the flight state.
      #  Defaults to "create-drop" when using an embedded database and no schema manager was detected.
      #  Otherwise, defaults to "none".
      ddl-auto: create-drop
    show-sql: true
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
      settings:
        trace: true